rules:
  empty-line-between-blocks: 0
  empty-args:
    - 1
    -
      include: true
  mixins-before-declarations:
    - 1
    -
      exclude: ['media', 'hi-dpi']
  nesting-depth:
    - 1
    -
      max-depth: 3
  bem-depth:
    - 1
    -
      max-depth: 2
  property-sort-order: 0
  indentation:
    - 1
    -
      size: tab
  space-between-parens:
    - 1
    -
      include: true
  no-qualifying-elements:
    - 1
    -
      allow-element-with-attribute: true
  brace-style:
    - 2
    -
      style: stroustrup
  class-name-format:
    - 2
    -
      convention: hyphenatedbem
  leading-zero:
    - 2
    -
      include: true
